- id: pt-appsec-hook
  name: OWASP Validator Hook
  description: Run OWASP validations using specialized LLM models.
  entry: python -m hooks.hook
  language: python
  types: [python]
  always_run: true
  fail_fast: true
  verbose: true